config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'home#index'
  devise_for :users
  resources :users

  resources :registrations
  post '/signup', to: 'registrations#signup', as: :signup
  get '/signup', to: 'registrations#new', as: :new_signup
  get '/send_otp', to: 'registrations#send_otp', as: :send_otp
  post '/verify_otp', to: 'registrations#verify_otp', as: :verify_otp

  resources :sessions
  post '/login', to: 'sessions#login', as: :login
  get '/login', to: 'sessions#new', as: :new_login
  get '/forgot_password', to: "sessions#forgot_password", as: :forgot_password
  post '/reset_password', to: "sessions#reset_password", as: :reset_password
  delete '/logout', to: 'sessions#logout', as: :logout

  resources :profiles 
  get '/edit_profile', to: "profiles#edit_user_profile", as: :edit_user_profile
  put '/update_profile', to: "profiles#update_user_profile", as: :update_user_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_FORMAT = /\A
  (?=.{8,})          # Must contain 8 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
  (?=.*[[:^alnum:]]) # Must contain a symbol
/x

  validates_presence_of :first_name, :last_name, :email, :password, :password_confirmation
  validates :password,   presence: true, 
  length: { in: Devise.password_length }, 
  format: { with: PASSWORD_FORMAT }, 
  confirmation: true, 
  on: :create, confirmation: {case_sensitive: true}
  validates :email, presence: true, format: Devise.email_regexp, uniqueness: {:case_sensitive => false}
  validates_uniqueness_of :phone_number, allow_nil: true, allow_blank: true

  has_one_attached :avatar
  validates :avatar, presence: {message: "Please upload your profile"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def edit_user_profile
        @user = User.find_by_id(params[:format])
        render 'edit_user_profile'
    end

    def update_user_profile
        @user = User.find_by_id(params[:id])
        if @user.update(user_params)
            flash[:success] = "You have updated your profile successfully."
            redirect_to root_path
        else
            flash[:danger] = @user.errors.full_messages.first
            redirect_to edit_user_profile_path(@user)
        end
    end

    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :phone_number, :city, :password, :password_confirmation, :avatar)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  protect_from_forgery
  before_action :current_user, only: [:new]
  def new
    @user = User.new
  end

  def signup
    user = User.new(user_params)
    if user.save
      user.otp = rand(10 ** 4)
      user.otp_expiration = Time.now
      user.save(validate: false)
      cookies[:user_id] = user.id
      redirect_to send_otp_path
    else
      flash[:danger]=user.errors.full_messages.first
      redirect_to new_registration_path
    end
  end

  def send_otp
    @current_user = User.find_by_id(cookies[:user_id])
    unless @current_user&.activated?
      SendOtpMailer.send_otp(@current_user).deliver_now
      flash[:success] = "We have sent an otp to your email."
      render 'send_otp'
    else
      redirect_to root_path
    end
  end

  def verify_otp
    user=User.find_by_email(params[:email])
    if (Time.now - user.otp_expiration) < 5.minutes
      if params[:otp].to_i == user.otp
          user.activated = true
          user.save(validate: false)
        flash[:success] = "Congrats! your account is verified successfully."
        redirect_to root_path
      else
        flash[:danger] = "Invalid OTP"
        redirect_to send_otp_path
      end
    else
      flash[:danger] = "OTP has been expired. We have sent you a new OTP"
      redirect_to send_otp_path
    end
  end

  def current_user
    @current_user = User.find_by_id(cookies[:user_id])
    redirect_to root_path if @current_user
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :city, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :current_user, only: [:new]

  def new
    @user = User.new
  end

  def login
    user = User.find_by_email(params[:user][:email])
    if user&.valid_password?(params[:user][:password])
      cookies[:user_id] = user.id
      flash[:success] = "Yay you have logged in"
      redirect_to root_path
    else
      flash[:danger]="Invalid user or password"
      redirect_to new_session_path
    end
  end

  def forgot_password
    render 'forgot_password'
  end

  def reset_password
    user = User.find_by_email(params[:email])
    if user
      temp_password = SecureRandom.hex(6)
      user.update(password: temp_password, password_confirmation: temp_password)
      ForgotPasswordMailer.forgot_password(user).deliver_now
      flash[:info] = "Your new password has been sent to your email."
      redirect_to login_path
    else
      flash[:danger] = "No user found with this email."
      redirect_to login_path
    end
  end

  def logout
    cookies.delete(:user_id)
    redirect_to new_login_path
  end

  private

  def current_user
    @current_user = User.find_by_id(cookies[:user_id])
    redirect_to root_path if @current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user = User.find_by_id(id: cookies[:id])
    end
end

app/helpers/home_helper.rb
module HomeHelper
    def logged_in
        @current_user = User.find_by_id(cookies[:user_id])
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
    def logged_in?
        !!cookies[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(cookies[:user_id])
    end
end

app/views/home/index.html.erb
<% if current_user and current_user.activated? %>
    <h1> Welcome to the my Network </h1>
<% elsif current_user and current_user.activated.nil? %>
    <h3>Please verify your email to continue </h3>
    <%= link_to "Verify Email", send_otp_path, class: "btn btn-success" %>
<% else %>
    <p> This is the landing page </p>
<% end %>

app/views/layouts/_navbar.html.erb
<%= javascript_include_tag 'navbar', 'data-turbolinks-track' => true, defer: true %>
<div class="container-fluid navbar-container">

  <div class="nav-mobile">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-2" aria-label="">
      <div class="search-bar">
        <form class="form-inline my-2 my-lg-0">
          <input class="search" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
      <a class="navbar-brand" href="#">My Site</a>
      <div class="ham-burger">
        <div class="ham-burger-icon"></div>
        <div class="ham-burger-icon"></div>
        <div class="ham-burger-icon"></div>
      </div>
    </nav>
  </div>

  <div class="user-dropdown">
    <ul class="dropdown" style="display:none">
      <% if !current_user %>
        <li class="nav-item active">
          <%= link_to "Signup", signup_path, class: "nav-link active" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= button_to "Edit", edit_user_profile_path(current_user), method: :get, data: {turbo: false}, class: "btn btn-link nav-link active profile-link" %>
        </li>

        <li class="nav-item">
          <%= button_to "Logout", logout_path({id: current_user.id}), method: :delete, data: {turbo: false}, class: "btn btn-link nav-link active profile-link" %>
        </li>
      <% end %>
    </ul>
  </div>

  <span class='nav-desktop'>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-2" aria-label="">
      <a class="navbar-brand" href="#">My Site</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <div class="search-bar">
            <form class="form-inline my-2 my-lg-0">
              <input class="search" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
          <% if !current_user %>
            <li class="nav-item active">
              <%= link_to "Signup", signup_path, class: "nav-link active" %>
            </li>

            <li class="nav-item active">
              <%= link_to "Login", login_path, class: "nav-link active" %>
            </li>
          <% end %>
        </ul>
      </div>

      <% if current_user %>
        <div class="profile-dropdown">
        <% if current_user&.avatar&.attached? %>
          <%= image_tag current_user.avatar, class: 'profile-image' %>
        <% end %>
          <ul class="dropdown-menu" style="display:none;">
            <li class="nav-item">
              <%= button_to "Edit", edit_user_profile_path(current_user), method: :get, data: {turbo: false}, class: "btn btn-link nav-link active profile-link" %>
            </li>

            <li class="nav-item">
              <%= button_to "Logout", logout_path({id: current_user.id}), method: :delete, data: {turbo: false}, class: "btn btn-link nav-link active profile-link" %>
            </li>
          </ul>
        </div>
      <% end %>
    </nav>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>SocialNetwork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, defer: true %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  </head>

  <body>
    <%= render "/layouts/navbar" %>
    <div class="body-content">
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %> alert-dismissible fade show mx-3 my-2" role="alert">
          <%= msg %>.
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/edit_user_profile.html.erb
<%= javascript_include_tag 'login_signup', 'data-turbolinks-track' => true %>
<div>
    <h1 class="text-center mt-2">Update your profile</h1>
    <div class="form-container">
        <%= form_with(model: @user, url: update_user_profile_path(@user), method: :put, remote: true) do |f| %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= hidden_field_tag :id, @user.id %>
        <div class="fields first-name-block">
            <%= f.label :first_name, "First name: " %>
            <%= f.text_field :first_name, value: @user&.first_name, class: "input-fields" %>
        </div>

        <div class="fields last-name-block">
            <%= f.label :last_name, "Last name: " %>
            <%= f.text_field :last_name, value: @user&.last_name, class: "input-fields" %>
        </div>

        <div class="fields email-block">
            <%= f.label :email, "Your email: " %>
            <%= f.email_field :email, value: @user&.email, class: "input-fields", disabled: true %>
        </div>

        <div class="fields password-block">
            <%= f.label :password, "Password: " %>
            <%= f.password_field :password, class: "input-fields" %>
        </div>

        <div class="fields confirm-block">
            <%= f.label :password_confirmation, "Re-enter Password: " %>
            <%= f.password_field :password_confirmation, class: "input-fields" %>
        </div>

        <div class="fields mobile-block">
            <%= f.label :phone_number, "Mobile number: " %>
            <%= f.telephone_field :phone_number, value: @user&.phone_number, class: "input-fields" %>
        </div>

        <div class="fields city-block">
            <%= f.label :city, "City: " %>
            <%= f.text_field :city, value: @user&.city, class: "input-fields" %>
        </div>

        <div class="fields">
            <%= f.label :avatar, "Profile Image " %>
            <%= f.file_field :avatar %>
        </div>

        <div class="form-submit">
            <%= f.submit "Update profile", class: "submit", id: "account-btn" %>
        </div>

        <% end %>
    </div>
</div>